### ISSUE TITLE
Article creation

### ISSUE THREAD

**Issue by dariuschira** [mirceachira/portfolio-manager-for-companies#7]
As a company representative (user), once I'm logged in, I want to be able to see a page where I can publish an article.

An article should have some basic fields: title, description, published date (date it was accepted by admin (see other issue related to this before!) not the date it was created, but we should record that too!).

The user should be able to fill in a basic form and hit submit.

**Comment by shrey1608** [comment]
can i work on this?

**Comment by dariuschira** [comment]
Hey @shrey1608 thanks for taking interest in this but this project is actually 'homework' of sorts. It a replacement for the internship period every student has to do during their final year at Babes Bolyai Maths and Computer Science faculty.

There are a few competing projects for the university portfolio manager but if this one wins I do hope it will remain open source so it can have other contributors :)

**Comment by shrey1608** [comment]
Ohh okay! Good luck with it !
